services:
  pgdatabase:
    image: postgres:16
    container_name: pgdatabase
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pgnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8085:80"
    networks:
      - pgnet

  ingest:   # ✅ NOW IT’S A SERVICE
    build: .
    depends_on:
      - pgdatabase
    networks:
      - pgnet
    command: >
      --user=root
      --password=root
      --host=pgdatabase
      --port=5432
      --db=ny_taxi
      --table_name=yellow_taxi_trips_2021_1
      --year=2021
      --month=1
      --chunksize=100000

networks:
  pgnet:

volumes:
  ny_taxi_postgres_data:
  pgadmin_data:
